#!/bin/bash
cd `dirname $0`
rm -f comm_tags
ctags -f comm_tags -R --c++-kinds=+p --fields=+iaS --extra=+q \
	/usr/include/*.h \
	/usr/include/netinet/\
	/usr/include/net/\
	/usr/include/arpa/\
	/usr/include/sys\
	/usr/include/bits\
    /usr/include/c++
	/usr/include/i386-linux-gnu/sys/\
	/usr/include/i386-linux-gnu/bits/\
	/usr/include/asm\
	/usr/include/asm-generic\
	/usr/include/arpa/\
	/usr/include/mysql/\
