#!/bin/bash
dec2ip () {
    local ip dec=$@
    for e in {3..0}
    do
        ((octet = dec / (256 ** e) ))
        ((dec -= octet * 256 ** e))
        ip+=$delim$octet
        delim=.
    done
    delim=""
    printf '%s  ' "$ip"
}

clearPath() {
    export PATH=$(echo $PATH | awk -F: '{ for (i = 1; i <= NF; i++) {if(arr[$i]!=$i){printf "%s:",$i;arr[$i]=$i;}}printf "\n"}')
}

ip2dec () {
    local a b c d ip=$@
    IFS=. read -r a b c d <<< "$ip"
    printf '%d\n' "$((a * 256 ** 3 + b * 256 ** 2 + c * 256 + d))"
}

function comm_put_ser() 
{
    user=$1
    ip_fix=$2
    port=$3
    passwd=$4
    sshpass -p"$passwd" scp -q -2 -P $port $6 $user@$ip_fix.$5:~/
}

function comm_get_ser() 
{
    user=$1
    ip_fix=$2
    port=$3
    passwd=$4
    sshpass -p"$passwd" scp -q -2 -P $port  $user@$ip_fix.$5:~/$6 . 
}

function alias_comm_cmd() 
{
    flag=$2
    user=$3
    ip_fix=$4
    port=$5
    passwd=$6
    user_flag=$7
    eval "alias c$flag$1$user_flag='sshpass  -p\"$passwd\" ssh -q -2 -p$port $user@$ip_fix.$1' "
    eval "alias put$flag$1$user_flag=' comm_put_ser $user $ip_fix $port \"$passwd\" $1 ' "
    eval "alias get$flag$1$user_flag=' comm_get_ser $user $ip_fix $port \"$passwd\" $1 ' "
}

function 2date()
{
    if [ "`uname`" eq "Darwin" ]; then
        date -r $1
    elif [ "`uname`" == "Linux" ]; then
        date -d @$1
        #date +"%F %T" -d "1970-01-01 UTC $1 seconds"
    fi
}

function 2ts()
{
    if [ "`uname`" == "Darwin" ]; then
        date -j -f "%Y-%m-%d %H:%M:%S" "$1" "+%s"
    elif [ "`uname`" == "Linux" ]; then
        date -d "$1" +%s
    fi
}


###### convert hexadecimal numbers to decimals
function dec()		{ printf "%d\n" $1; }

###### convert decimals to hexadecimal numbers
function hex()		{ printf "0x%08x\n" $1; }

function alias_server()
{
    local idc=$1
    local lastip=`echo $2 | awk -F. '{print $4}'`
    alias go.$idc$lastip="ssh -p 20220 -i ~/.ssh/devops.pem devops@$2" 
    alias upload.$idc$lastip="upload_() { scp -P 20220 -i ~/.ssh/devops.pem -C -r \$1 devops@$2:~/; } && upload_ "
    alias download.$idc$lastip="download_() { scp -P 20220 -i ~/.ssh/devops.pem -C devops@$2:~/\"\$1\"; } && download_ "
}
