#!/bin/bash
cd `dirname $0`
rm -f tags
ctags -R --c++-kinds=+p --fields=+iaS --extra=+q /usr/include/*.h \
	 /usr/include/netinet/\
	 /usr/include/net/\
	 /usr/include/arpa/\
	 /usr/include/i386-linux-gnu/sys\
	 /usr/include/i386-linux-gnu/bits\
